// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum CalDavFreshness { disabled, loading, current, stale, error }

class CalDavSyncState {
  final CalDavFreshness freshness;
  final PlatformInt64? lastSuccessUnixSecs;
  final String? error;
  final bool hasCachedData;

  const CalDavSyncState({
    required this.freshness,
    this.lastSuccessUnixSecs,
    this.error,
    required this.hasCachedData,
  });

  @override
  int get hashCode =>
      freshness.hashCode ^
      lastSuccessUnixSecs.hashCode ^
      error.hashCode ^
      hasCachedData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalDavSyncState &&
          runtimeType == other.runtimeType &&
          freshness == other.freshness &&
          lastSuccessUnixSecs == other.lastSuccessUnixSecs &&
          error == other.error &&
          hasCachedData == other.hasCachedData;
}

/// UI-safe normalized VTODO fields. No time label or credential can enter this
/// model; completion instants are retained only as sortable Unix timestamps.
class NormalizedTask {
  final TaskResourceIdentity identity;
  final String uid;
  final String title;
  final String collectionName;

  /// Machine-local `YYYY-MM-DD`, or `None` for an undated task.
  final String? dueDate;

  /// UTC Unix seconds, used for local completion-day filtering and ordering.
  final PlatformInt64? completedAtUnixSecs;
  final TaskStatus status;
  final TaskPriority priority;

  const NormalizedTask({
    required this.identity,
    required this.uid,
    required this.title,
    required this.collectionName,
    this.dueDate,
    this.completedAtUnixSecs,
    required this.status,
    required this.priority,
  });

  @override
  int get hashCode =>
      identity.hashCode ^
      uid.hashCode ^
      title.hashCode ^
      collectionName.hashCode ^
      dueDate.hashCode ^
      completedAtUnixSecs.hashCode ^
      status.hashCode ^
      priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NormalizedTask &&
          runtimeType == other.runtimeType &&
          identity == other.identity &&
          uid == other.uid &&
          title == other.title &&
          collectionName == other.collectionName &&
          dueDate == other.dueDate &&
          completedAtUnixSecs == other.completedAtUnixSecs &&
          status == other.status &&
          priority == other.priority;
}

enum TaskPriority { doNow, urgent, high, medium, low }

/// Stable identity used by snapshots and completion requests.
class TaskResourceIdentity {
  final String collectionHref;
  final String resourceHref;

  const TaskResourceIdentity({
    required this.collectionHref,
    required this.resourceHref,
  });

  @override
  int get hashCode => collectionHref.hashCode ^ resourceHref.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskResourceIdentity &&
          runtimeType == other.runtimeType &&
          collectionHref == other.collectionHref &&
          resourceHref == other.resourceHref;
}

enum TaskStatus { active, completed, cancelled }
