name: alicebar
description: "A Flutter-first Wayland bar for wlroots compositors."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
