name: alicebar
description: "A Flutter-first Wayland bar for wlroots compositors."
publish_to: "none"
version: 2026.2.0

environment:
  sdk: ^3.10.4

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.12.0
  intl: ^0.20.2
  material_ui: ^0.0.1
  phosphoricons_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: NimbusSansDOT
      fonts:
        - asset: fonts/NimbusSans-Regular.ttf
        - asset: fonts/NimbusSans-Italic.ttf
          style: italic
        - asset: fonts/NimbusSans-Bold.ttf
          weight: 700
        - asset: fonts/NimbusSans-BoldItalic.ttf
          weight: 700
          style: italic
