// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'prompt.freezed.dart';

@freezed
sealed class PromptResponse with _$PromptResponse {
  const PromptResponse._();

  const factory PromptResponse.pinCode(String field0) = PromptResponse_PinCode;
  const factory PromptResponse.passkey(int field0) = PromptResponse_Passkey;
  const factory PromptResponse.accept() = PromptResponse_Accept;
  const factory PromptResponse.deny() = PromptResponse_Deny;
  const factory PromptResponse.cancel() = PromptResponse_Cancel;
}
