// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'config.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state.dart';

/// Start streaming `BarSnapshot` values to Dart.
///
/// Dart subscribes once; Rust pushes a new snapshot whenever system state
/// changes (workspaces, media, network, tray, stats, clock).
Stream<BarSnapshot> watchBarSnapshots() =>
    RustLib.instance.api.crateApiWatchBarSnapshots();

/// Register the Dart-side sink for panel show/hide commands.
///
/// The C++ showPanel/hidePanel MethodChannel handler calls
/// `alice_notify_panel_show` / `alice_notify_panel_hide` (see `lib.rs`),
/// which push to this sink.
Stream<PanelCommand?> watchPanelCommands() =>
    RustLib.instance.api.crateApiWatchPanelCommands();

/// Load the user's config file (or defaults if missing / unreadable).
Future<AliceConfig> loadConfig() => RustLib.instance.api.crateApiLoadConfig();

/// Send an MPRIS media control action: `"previous"`, `"playPause"`, or `"next"`.
Future<bool> sendMediaAction({required String action}) =>
    RustLib.instance.api.crateApiSendMediaAction(action: action);

/// Seek the active MPRIS player to the given absolute position in microseconds.
Future<bool> seekMedia({required PlatformInt64 positionMicros}) =>
    RustLib.instance.api.crateApiSeekMedia(positionMicros: positionMicros);

/// Focus the sway workspace with the given label.
Future<bool> focusWorkspace({required String label}) =>
    RustLib.instance.api.crateApiFocusWorkspace(label: label);

/// Send a StatusNotifier tray action (`"activate"`, `"secondaryActivate"`, `"contextMenu"`).
Future<bool> sendTrayAction({
  required String serviceName,
  required String objectPath,
  required String action,
  required int x,
  required int y,
}) => RustLib.instance.api.crateApiSendTrayAction(
  serviceName: serviceName,
  objectPath: objectPath,
  action: action,
  x: x,
  y: y,
);

/// Execute a power management action: `"lock"`, `"lockAndSuspend"`, `"restart"`, `"poweroff"`.
///
/// Reads the configured shell command from the user's config and runs it via `/bin/sh -c`.
Future<bool> executePowerAction({required String action}) =>
    RustLib.instance.api.crateApiExecutePowerAction(action: action);

/// Fetch Google Calendar events for the given date (`"YYYY-MM-DD"`).
///
/// Returns immediately. On first call without a stored token this initiates
/// a device-flow: `status == "needs_auth"` with `auth_url` / `auth_code`.
/// Subsequent calls while the user is completing auth return `status ==
/// "polling"`. Once authorised, `status == "ready"` with the events list.
/// If calendar is not configured in the user's config, returns
/// `status == "not_configured"` and the events section stays hidden.
Future<CalendarFetchResult> fetchCalendarEvents({required String date}) =>
    RustLib.instance.api.crateApiFetchCalendarEvents(date: date);

/// A command forwarded to Dart via `watch_panel_commands` whenever a panel
/// should be shown. `view_id` identifies the Flutter view to render into.
class PanelCommand {
  final String panelId;
  final PlatformInt64 viewId;
  final bool includeIconBytes;
  final double anchorX;
  final double anchorY;
  final double width;
  final double height;

  const PanelCommand({
    required this.panelId,
    required this.viewId,
    required this.includeIconBytes,
    required this.anchorX,
    required this.anchorY,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      panelId.hashCode ^
      viewId.hashCode ^
      includeIconBytes.hashCode ^
      anchorX.hashCode ^
      anchorY.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PanelCommand &&
          runtimeType == other.runtimeType &&
          panelId == other.panelId &&
          viewId == other.viewId &&
          includeIconBytes == other.includeIconBytes &&
          anchorX == other.anchorX &&
          anchorY == other.anchorY &&
          width == other.width &&
          height == other.height;
}
