// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'config.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state.dart';

/// Start streaming `BarSnapshot` values to Dart.
///
/// Dart subscribes once; Rust pushes a new snapshot whenever system state
/// changes (workspaces, media, network, tray, stats, clock).
Stream<BarSnapshot> watchBarSnapshots() =>
    RustLib.instance.api.crateApiWatchBarSnapshots();

/// Register the Dart-side sink for panel show/hide commands (panel process only).
///
/// The panel process's C++ socket listener calls `alice_notify_panel_show` /
/// `alice_notify_panel_hide` (see `lib.rs`), which push to this sink.
Stream<PanelCommand?> watchPanelCommands() =>
    RustLib.instance.api.crateApiWatchPanelCommands();

/// Load the user's config file (or defaults if missing / unreadable).
Future<AliceConfig> loadConfig() => RustLib.instance.api.crateApiLoadConfig();

/// Send an MPRIS media control action: `"previous"`, `"playPause"`, or `"next"`.
Future<bool> sendMediaAction({required String action}) =>
    RustLib.instance.api.crateApiSendMediaAction(action: action);

/// Seek the active MPRIS player to the given absolute position in microseconds.
Future<bool> seekMedia({required PlatformInt64 positionMicros}) =>
    RustLib.instance.api.crateApiSeekMedia(positionMicros: positionMicros);

/// Focus the sway workspace with the given label.
Future<bool> focusWorkspace({required String label}) =>
    RustLib.instance.api.crateApiFocusWorkspace(label: label);

/// Send a StatusNotifier tray action (`"activate"`, `"secondaryActivate"`, `"contextMenu"`).
Future<bool> sendTrayAction({
  required String serviceName,
  required String objectPath,
  required String action,
  required int x,
  required int y,
}) => RustLib.instance.api.crateApiSendTrayAction(
  serviceName: serviceName,
  objectPath: objectPath,
  action: action,
  x: x,
  y: y,
);

/// Execute a power management action: `"lock"`, `"lockAndSuspend"`, `"restart"`, `"poweroff"`.
///
/// Reads the configured shell command from the user's config and runs it via `/bin/sh -c`.
Future<bool> executePowerAction({required String action}) =>
    RustLib.instance.api.crateApiExecutePowerAction(action: action);

/// A command sent from the bar process to the panel process over the Unix socket,
/// forwarded to Dart via `watch_panel_commands`.
class PanelCommand {
  final String panelId;
  final bool includeIconBytes;
  final double anchorX;
  final double anchorY;
  final double width;
  final double height;

  const PanelCommand({
    required this.panelId,
    required this.includeIconBytes,
    required this.anchorX,
    required this.anchorY,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      panelId.hashCode ^
      includeIconBytes.hashCode ^
      anchorX.hashCode ^
      anchorY.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PanelCommand &&
          runtimeType == other.runtimeType &&
          panelId == other.panelId &&
          includeIconBytes == other.includeIconBytes &&
          anchorX == other.anchorX &&
          anchorY == other.anchorY &&
          width == other.width &&
          height == other.height;
}
