// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'caldav/models.dart';
import 'config.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Start streaming `BarSnapshot` values to Dart.
///
/// Dart subscribes once; Rust pushes a new snapshot whenever system state
/// changes (workspaces, media, network, tray, stats, clock).
Stream<BarSnapshot> watchBarSnapshots() =>
    RustLib.instance.api.crateApiWatchBarSnapshots();

/// Register the Dart-side sink for panel show/hide commands.
///
/// The C++ showPanel/hidePanel MethodChannel handler calls
/// `alice_notify_panel_show` / `alice_notify_panel_hide` (see `lib.rs`),
/// which push to this sink.
Stream<PanelCommand?> watchPanelCommands() =>
    RustLib.instance.api.crateApiWatchPanelCommands();

/// Load the user's config file (or defaults if missing / unreadable).
Future<AliceUiConfig> loadConfig() => RustLib.instance.api.crateApiLoadConfig();

/// Coalesce a panel-open or manual CalDAV refresh into the runtime service.
Future<bool> requestCaldavRefresh() =>
    RustLib.instance.api.crateApiRequestCaldavRefresh();

/// Complete or un-complete a stable CalDAV task resource identity.
Future<void> setCaldavTaskCompleted({
  required TaskResourceIdentity identity,
  required bool completed,
}) => RustLib.instance.api.crateApiSetCaldavTaskCompleted(
  identity: identity,
  completed: completed,
);

/// Send an MPRIS media control action: `"previous"`, `"playPause"`, or `"next"`.
Future<bool> sendMediaAction({required String action}) =>
    RustLib.instance.api.crateApiSendMediaAction(action: action);

/// Seek the active MPRIS player to the given absolute position in microseconds.
Future<bool> seekMedia({required PlatformInt64 positionMicros}) =>
    RustLib.instance.api.crateApiSeekMedia(positionMicros: positionMicros);

/// Focus the sway workspace with the given label.
Future<bool> focusWorkspace({required String label}) =>
    RustLib.instance.api.crateApiFocusWorkspace(label: label);

/// Send a StatusNotifier tray action (`"activate"`, `"secondaryActivate"`, `"contextMenu"`).
Future<bool> sendTrayAction({
  required String serviceName,
  required String objectPath,
  required String action,
  required int x,
  required int y,
}) => RustLib.instance.api.crateApiSendTrayAction(
  serviceName: serviceName,
  objectPath: objectPath,
  action: action,
  x: x,
  y: y,
);

/// Execute a power management action: `"lock"`, `"lockAndSuspend"`, `"restart"`, `"poweroff"`.
///
/// Reads the configured shell command from the user's config and runs it via `/bin/sh -c`.
Future<bool> executePowerAction({required String action}) =>
    RustLib.instance.api.crateApiExecutePowerAction(action: action);

/// Remove a single notification by ID and trigger a snapshot update.
///
/// Emits the `NotificationClosed` D-Bus signal with reason 2 (dismissed by user).
Future<void> dismissNotification({required int id}) =>
    RustLib.instance.api.crateApiDismissNotification(id: id);

/// Remove all notifications and trigger a snapshot update.
Future<void> dismissAllNotifications() =>
    RustLib.instance.api.crateApiDismissAllNotifications();

/// Mark a notification as read and trigger a snapshot update.
///
/// Use this when the notification panel opens so the unread badge count updates.
Future<void> markNotificationRead({required int id}) =>
    RustLib.instance.api.crateApiMarkNotificationRead(id: id);

/// Emit the `ActionInvoked` D-Bus signal for a notification action button.
///
/// This notifies the originating application that the user clicked an action.
Future<void> invokeNotificationAction({
  required int id,
  required String actionKey,
}) => RustLib.instance.api.crateApiInvokeNotificationAction(
  id: id,
  actionKey: actionKey,
);

/// Fetch Google Calendar events for the given date (`"YYYY-MM-DD"`).
///
/// Returns immediately. On first call without a stored token this initiates
/// a device-flow: `status == "needs_auth"` with `auth_url` / `auth_code`.
/// Subsequent calls while the user is completing auth return `status ==
/// "polling"`. Once authorised, `status == "ready"` with the events list.
/// If calendar is not configured in the user's config, returns
/// `status == "not_configured"` and the events section stays hidden.
Future<CalendarFetchResult> fetchCalendarEvents({required String date}) =>
    RustLib.instance.api.crateApiFetchCalendarEvents(date: date);

/// Secret-free configuration contract returned to Flutter.
class AliceUiConfig {
  final ThemeMode themeMode;
  final String accentColor;
  final bool transparentTopBar;
  final bool showNetworkLabel;
  final int maxVisibleTrayItems;
  final String? localTimeZoneLabel;
  final List<TimeZoneConfig> timeZones;
  final PowerCommandConfig powerCommands;
  final int panelTopGapPx;
  final CalendarConfig? calendar;
  final CalDavUiConfig? caldav;
  final NotificationConfig notifications;
  final WeatherConfig weather;

  const AliceUiConfig({
    required this.themeMode,
    required this.accentColor,
    required this.transparentTopBar,
    required this.showNetworkLabel,
    required this.maxVisibleTrayItems,
    this.localTimeZoneLabel,
    required this.timeZones,
    required this.powerCommands,
    required this.panelTopGapPx,
    this.calendar,
    this.caldav,
    required this.notifications,
    required this.weather,
  });

  @override
  int get hashCode =>
      themeMode.hashCode ^
      accentColor.hashCode ^
      transparentTopBar.hashCode ^
      showNetworkLabel.hashCode ^
      maxVisibleTrayItems.hashCode ^
      localTimeZoneLabel.hashCode ^
      timeZones.hashCode ^
      powerCommands.hashCode ^
      panelTopGapPx.hashCode ^
      calendar.hashCode ^
      caldav.hashCode ^
      notifications.hashCode ^
      weather.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AliceUiConfig &&
          runtimeType == other.runtimeType &&
          themeMode == other.themeMode &&
          accentColor == other.accentColor &&
          transparentTopBar == other.transparentTopBar &&
          showNetworkLabel == other.showNetworkLabel &&
          maxVisibleTrayItems == other.maxVisibleTrayItems &&
          localTimeZoneLabel == other.localTimeZoneLabel &&
          timeZones == other.timeZones &&
          powerCommands == other.powerCommands &&
          panelTopGapPx == other.panelTopGapPx &&
          calendar == other.calendar &&
          caldav == other.caldav &&
          notifications == other.notifications &&
          weather == other.weather;
}

/// Non-secret CalDAV settings needed to decide whether and how to render UI.
class CalDavUiConfig {
  final String principalUrl;
  final bool allowHttp;
  final String username;
  final List<String> collectionHrefs;
  final int pollIntervalSecs;
  final String? caCertificatePath;

  const CalDavUiConfig({
    required this.principalUrl,
    required this.allowHttp,
    required this.username,
    required this.collectionHrefs,
    required this.pollIntervalSecs,
    this.caCertificatePath,
  });

  @override
  int get hashCode =>
      principalUrl.hashCode ^
      allowHttp.hashCode ^
      username.hashCode ^
      collectionHrefs.hashCode ^
      pollIntervalSecs.hashCode ^
      caCertificatePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalDavUiConfig &&
          runtimeType == other.runtimeType &&
          principalUrl == other.principalUrl &&
          allowHttp == other.allowHttp &&
          username == other.username &&
          collectionHrefs == other.collectionHrefs &&
          pollIntervalSecs == other.pollIntervalSecs &&
          caCertificatePath == other.caCertificatePath;
}

/// A command forwarded to Dart via `watch_panel_commands` whenever a panel
/// should be shown. `view_id` identifies the Flutter view to render into.
class PanelCommand {
  final String panelId;
  final PlatformInt64 viewId;
  final bool includeIconBytes;
  final double anchorX;
  final double anchorY;
  final double width;
  final double height;

  const PanelCommand({
    required this.panelId,
    required this.viewId,
    required this.includeIconBytes,
    required this.anchorX,
    required this.anchorY,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      panelId.hashCode ^
      viewId.hashCode ^
      includeIconBytes.hashCode ^
      anchorX.hashCode ^
      anchorY.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PanelCommand &&
          runtimeType == other.runtimeType &&
          panelId == other.panelId &&
          viewId == other.viewId &&
          includeIconBytes == other.includeIconBytes &&
          anchorX == other.anchorX &&
          anchorY == other.anchorY &&
          width == other.width &&
          height == other.height;
}
