// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AliceConfig {
  final ThemeMode themeMode;
  final String accentColor;
  final bool showNetworkLabel;
  final int maxVisibleTrayItems;
  final String? localTimeZoneLabel;
  final List<TimeZoneConfig> timeZones;
  final PowerCommandConfig powerCommands;

  const AliceConfig({
    required this.themeMode,
    required this.accentColor,
    required this.showNetworkLabel,
    required this.maxVisibleTrayItems,
    this.localTimeZoneLabel,
    required this.timeZones,
    required this.powerCommands,
  });

  @override
  int get hashCode =>
      themeMode.hashCode ^
      accentColor.hashCode ^
      showNetworkLabel.hashCode ^
      maxVisibleTrayItems.hashCode ^
      localTimeZoneLabel.hashCode ^
      timeZones.hashCode ^
      powerCommands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AliceConfig &&
          runtimeType == other.runtimeType &&
          themeMode == other.themeMode &&
          accentColor == other.accentColor &&
          showNetworkLabel == other.showNetworkLabel &&
          maxVisibleTrayItems == other.maxVisibleTrayItems &&
          localTimeZoneLabel == other.localTimeZoneLabel &&
          timeZones == other.timeZones &&
          powerCommands == other.powerCommands;
}

class PowerCommandConfig {
  final String lock;
  final String lockAndSuspend;
  final String restart;
  final String poweroff;

  const PowerCommandConfig({
    required this.lock,
    required this.lockAndSuspend,
    required this.restart,
    required this.poweroff,
  });

  @override
  int get hashCode =>
      lock.hashCode ^
      lockAndSuspend.hashCode ^
      restart.hashCode ^
      poweroff.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PowerCommandConfig &&
          runtimeType == other.runtimeType &&
          lock == other.lock &&
          lockAndSuspend == other.lockAndSuspend &&
          restart == other.restart &&
          poweroff == other.poweroff;
}

enum ThemeMode { system, light, dark }

class TimeZoneConfig {
  final String label;
  final int offsetHours;

  const TimeZoneConfig({required this.label, required this.offsetHours});

  @override
  int get hashCode => label.hashCode ^ offsetHours.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeZoneConfig &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          offsetHours == other.offsetHours;
}
