// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BatteryConfig {
  final bool enable;
  final String? deviceName;

  const BatteryConfig({required this.enable, this.deviceName});

  @override
  int get hashCode => enable.hashCode ^ deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatteryConfig &&
          runtimeType == other.runtimeType &&
          enable == other.enable &&
          deviceName == other.deviceName;
}

class CalendarConfig {
  final String googleClientId;
  final String googleClientSecret;

  /// How often (in seconds) to poll for calendar changes via incremental sync.
  final int pollIntervalSecs;

  const CalendarConfig({
    required this.googleClientId,
    required this.googleClientSecret,
    required this.pollIntervalSecs,
  });

  @override
  int get hashCode =>
      googleClientId.hashCode ^
      googleClientSecret.hashCode ^
      pollIntervalSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarConfig &&
          runtimeType == other.runtimeType &&
          googleClientId == other.googleClientId &&
          googleClientSecret == other.googleClientSecret &&
          pollIntervalSecs == other.pollIntervalSecs;
}

class NotificationConfig {
  /// How long (ms) before the freedesktop server auto-dismisses. 0 = never expire.
  final int defaultTimeoutMs;

  /// Whether newly received notifications should appear as floating popups.
  final bool showNotificationPopup;

  /// How long (ms) popup cards remain visible. 0 = never auto-expire.
  final int notificationDisplayTimeMs;

  /// Whether critical notification popups are allowed to auto-expire.
  final bool expireCriticalNotifications;

  const NotificationConfig({
    required this.defaultTimeoutMs,
    required this.showNotificationPopup,
    required this.notificationDisplayTimeMs,
    required this.expireCriticalNotifications,
  });

  @override
  int get hashCode =>
      defaultTimeoutMs.hashCode ^
      showNotificationPopup.hashCode ^
      notificationDisplayTimeMs.hashCode ^
      expireCriticalNotifications.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationConfig &&
          runtimeType == other.runtimeType &&
          defaultTimeoutMs == other.defaultTimeoutMs &&
          showNotificationPopup == other.showNotificationPopup &&
          notificationDisplayTimeMs == other.notificationDisplayTimeMs &&
          expireCriticalNotifications == other.expireCriticalNotifications;
}

class PowerCommandConfig {
  final String lock;
  final String lockAndSuspend;
  final String restart;
  final String poweroff;

  const PowerCommandConfig({
    required this.lock,
    required this.lockAndSuspend,
    required this.restart,
    required this.poweroff,
  });

  @override
  int get hashCode =>
      lock.hashCode ^
      lockAndSuspend.hashCode ^
      restart.hashCode ^
      poweroff.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PowerCommandConfig &&
          runtimeType == other.runtimeType &&
          lock == other.lock &&
          lockAndSuspend == other.lockAndSuspend &&
          restart == other.restart &&
          poweroff == other.poweroff;
}

enum ThemeMode { system, light, dark }

class TimeZoneConfig {
  final String label;
  final int offsetHours;

  const TimeZoneConfig({required this.label, required this.offsetHours});

  @override
  int get hashCode => label.hashCode ^ offsetHours.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeZoneConfig &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          offsetHours == other.offsetHours;
}

class WeatherConfig {
  final bool enable;
  final String? pirateWeatherKey;
  final double? forecastLat;
  final double? forecastLong;
  final String forecastLanguage;
  final String forecastUnits;
  final int refreshInterval;
  final String? locationLabel;

  const WeatherConfig({
    required this.enable,
    this.pirateWeatherKey,
    this.forecastLat,
    this.forecastLong,
    required this.forecastLanguage,
    required this.forecastUnits,
    required this.refreshInterval,
    this.locationLabel,
  });

  @override
  int get hashCode =>
      enable.hashCode ^
      pirateWeatherKey.hashCode ^
      forecastLat.hashCode ^
      forecastLong.hashCode ^
      forecastLanguage.hashCode ^
      forecastUnits.hashCode ^
      refreshInterval.hashCode ^
      locationLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherConfig &&
          runtimeType == other.runtimeType &&
          enable == other.enable &&
          pirateWeatherKey == other.pirateWeatherKey &&
          forecastLat == other.forecastLat &&
          forecastLong == other.forecastLong &&
          forecastLanguage == other.forecastLanguage &&
          forecastUnits == other.forecastUnits &&
          refreshInterval == other.refreshInterval &&
          locationLabel == other.locationLabel;
}
