// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AliceConfig {
  final ThemeMode themeMode;
  final String accentColor;
  final bool transparentTopBar;
  final bool showNetworkLabel;
  final int maxVisibleTrayItems;
  final String? localTimeZoneLabel;
  final List<TimeZoneConfig> timeZones;
  final PowerCommandConfig powerCommands;
  final int panelTopGapPx;
  final CalendarConfig? calendar;
  final NotificationConfig notifications;

  const AliceConfig({
    required this.themeMode,
    required this.accentColor,
    required this.transparentTopBar,
    required this.showNetworkLabel,
    required this.maxVisibleTrayItems,
    this.localTimeZoneLabel,
    required this.timeZones,
    required this.powerCommands,
    required this.panelTopGapPx,
    this.calendar,
    required this.notifications,
  });

  @override
  int get hashCode =>
      themeMode.hashCode ^
      accentColor.hashCode ^
      transparentTopBar.hashCode ^
      showNetworkLabel.hashCode ^
      maxVisibleTrayItems.hashCode ^
      localTimeZoneLabel.hashCode ^
      timeZones.hashCode ^
      powerCommands.hashCode ^
      panelTopGapPx.hashCode ^
      calendar.hashCode ^
      notifications.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AliceConfig &&
          runtimeType == other.runtimeType &&
          themeMode == other.themeMode &&
          accentColor == other.accentColor &&
          transparentTopBar == other.transparentTopBar &&
          showNetworkLabel == other.showNetworkLabel &&
          maxVisibleTrayItems == other.maxVisibleTrayItems &&
          localTimeZoneLabel == other.localTimeZoneLabel &&
          timeZones == other.timeZones &&
          powerCommands == other.powerCommands &&
          panelTopGapPx == other.panelTopGapPx &&
          calendar == other.calendar &&
          notifications == other.notifications;
}

class CalendarConfig {
  final String googleClientId;
  final String googleClientSecret;

  /// How often (in seconds) to poll for calendar changes via incremental sync.
  final int pollIntervalSecs;

  const CalendarConfig({
    required this.googleClientId,
    required this.googleClientSecret,
    required this.pollIntervalSecs,
  });

  @override
  int get hashCode =>
      googleClientId.hashCode ^
      googleClientSecret.hashCode ^
      pollIntervalSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarConfig &&
          runtimeType == other.runtimeType &&
          googleClientId == other.googleClientId &&
          googleClientSecret == other.googleClientSecret &&
          pollIntervalSecs == other.pollIntervalSecs;
}

class NotificationConfig {
  /// How long (ms) before the freedesktop server auto-dismisses. 0 = never expire.
  final int defaultTimeoutMs;

  /// Whether newly received notifications should appear as floating popups.
  final bool showNotificationPopup;

  /// How long (ms) popup cards remain visible. 0 = never auto-expire.
  final int notificationDisplayTimeMs;

  /// Whether critical notification popups are allowed to auto-expire.
  final bool expireCriticalNotifications;

  const NotificationConfig({
    required this.defaultTimeoutMs,
    required this.showNotificationPopup,
    required this.notificationDisplayTimeMs,
    required this.expireCriticalNotifications,
  });

  @override
  int get hashCode =>
      defaultTimeoutMs.hashCode ^
      showNotificationPopup.hashCode ^
      notificationDisplayTimeMs.hashCode ^
      expireCriticalNotifications.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationConfig &&
          runtimeType == other.runtimeType &&
          defaultTimeoutMs == other.defaultTimeoutMs &&
          showNotificationPopup == other.showNotificationPopup &&
          notificationDisplayTimeMs == other.notificationDisplayTimeMs &&
          expireCriticalNotifications == other.expireCriticalNotifications;
}

class PowerCommandConfig {
  final String lock;
  final String lockAndSuspend;
  final String restart;
  final String poweroff;

  const PowerCommandConfig({
    required this.lock,
    required this.lockAndSuspend,
    required this.restart,
    required this.poweroff,
  });

  @override
  int get hashCode =>
      lock.hashCode ^
      lockAndSuspend.hashCode ^
      restart.hashCode ^
      poweroff.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PowerCommandConfig &&
          runtimeType == other.runtimeType &&
          lock == other.lock &&
          lockAndSuspend == other.lockAndSuspend &&
          restart == other.restart &&
          poweroff == other.poweroff;
}

enum ThemeMode { system, light, dark }

class TimeZoneConfig {
  final String label;
  final int offsetHours;

  const TimeZoneConfig({required this.label, required this.offsetHours});

  @override
  int get hashCode => label.hashCode ^ offsetHours.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeZoneConfig &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          offsetHours == other.offsetHours;
}
