// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'config.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'state.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<BarSnapshot> dco_decode_StreamSink_bar_snapshot_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PanelCommand?>
  dco_decode_StreamSink_opt_box_autoadd_panel_command_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AliceConfig dco_decode_alice_config(dynamic raw);

  @protected
  BarSnapshot dco_decode_bar_snapshot(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MediaSnapshot dco_decode_box_autoadd_media_snapshot(dynamic raw);

  @protected
  PanelCommand dco_decode_box_autoadd_panel_command(dynamic raw);

  @protected
  ClockSnapshot dco_decode_clock_snapshot(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TimeZoneConfig> dco_decode_list_time_zone_config(dynamic raw);

  @protected
  List<TrayItemSnapshot> dco_decode_list_tray_item_snapshot(dynamic raw);

  @protected
  List<WorkspaceSnapshot> dco_decode_list_workspace_snapshot(dynamic raw);

  @protected
  MediaSnapshot dco_decode_media_snapshot(dynamic raw);

  @protected
  NetworkKind dco_decode_network_kind(dynamic raw);

  @protected
  NetworkSnapshot dco_decode_network_snapshot(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MediaSnapshot? dco_decode_opt_box_autoadd_media_snapshot(dynamic raw);

  @protected
  PanelCommand? dco_decode_opt_box_autoadd_panel_command(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PanelCommand dco_decode_panel_command(dynamic raw);

  @protected
  PowerCommandConfig dco_decode_power_command_config(dynamic raw);

  @protected
  ThemeMode dco_decode_theme_mode(dynamic raw);

  @protected
  TimeZoneConfig dco_decode_time_zone_config(dynamic raw);

  @protected
  TrayItemSnapshot dco_decode_tray_item_snapshot(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorkspaceSnapshot dco_decode_workspace_snapshot(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<BarSnapshot> sse_decode_StreamSink_bar_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PanelCommand?>
  sse_decode_StreamSink_opt_box_autoadd_panel_command_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AliceConfig sse_decode_alice_config(SseDeserializer deserializer);

  @protected
  BarSnapshot sse_decode_bar_snapshot(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MediaSnapshot sse_decode_box_autoadd_media_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  PanelCommand sse_decode_box_autoadd_panel_command(
    SseDeserializer deserializer,
  );

  @protected
  ClockSnapshot sse_decode_clock_snapshot(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TimeZoneConfig> sse_decode_list_time_zone_config(
    SseDeserializer deserializer,
  );

  @protected
  List<TrayItemSnapshot> sse_decode_list_tray_item_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceSnapshot> sse_decode_list_workspace_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  MediaSnapshot sse_decode_media_snapshot(SseDeserializer deserializer);

  @protected
  NetworkKind sse_decode_network_kind(SseDeserializer deserializer);

  @protected
  NetworkSnapshot sse_decode_network_snapshot(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MediaSnapshot? sse_decode_opt_box_autoadd_media_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  PanelCommand? sse_decode_opt_box_autoadd_panel_command(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PanelCommand sse_decode_panel_command(SseDeserializer deserializer);

  @protected
  PowerCommandConfig sse_decode_power_command_config(
    SseDeserializer deserializer,
  );

  @protected
  ThemeMode sse_decode_theme_mode(SseDeserializer deserializer);

  @protected
  TimeZoneConfig sse_decode_time_zone_config(SseDeserializer deserializer);

  @protected
  TrayItemSnapshot sse_decode_tray_item_snapshot(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorkspaceSnapshot sse_decode_workspace_snapshot(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bar_snapshot_Sse(
    RustStreamSink<BarSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_opt_box_autoadd_panel_command_Sse(
    RustStreamSink<PanelCommand?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_alice_config(AliceConfig self, SseSerializer serializer);

  @protected
  void sse_encode_bar_snapshot(BarSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_media_snapshot(
    MediaSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_panel_command(
    PanelCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clock_snapshot(ClockSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_time_zone_config(
    List<TimeZoneConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tray_item_snapshot(
    List<TrayItemSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_snapshot(
    List<WorkspaceSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_snapshot(MediaSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_network_kind(NetworkKind self, SseSerializer serializer);

  @protected
  void sse_encode_network_snapshot(
    NetworkSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_media_snapshot(
    MediaSnapshot? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_panel_command(
    PanelCommand? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_panel_command(PanelCommand self, SseSerializer serializer);

  @protected
  void sse_encode_power_command_config(
    PowerCommandConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_theme_mode(ThemeMode self, SseSerializer serializer);

  @protected
  void sse_encode_time_zone_config(
    TimeZoneConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tray_item_snapshot(
    TrayItemSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_snapshot(
    WorkspaceSnapshot self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
