// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'config.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1353393966;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'alice_platform',
        ioDirectory: 'native/alice_platform/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiExecutePowerAction({required String action});

  Future<bool> crateApiFocusWorkspace({required String label});

  Future<AliceConfig> crateApiLoadConfig();

  Future<bool> crateApiSeekMedia({required PlatformInt64 positionMicros});

  Future<bool> crateApiSendMediaAction({required String action});

  Future<bool> crateApiSendTrayAction({
    required String serviceName,
    required String objectPath,
    required String action,
    required int x,
    required int y,
  });

  Stream<BarSnapshot> crateApiWatchBarSnapshots();

  Stream<PanelCommand?> crateApiWatchPanelCommands();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiExecutePowerAction({required String action}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(action, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExecutePowerActionConstMeta,
        argValues: [action],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExecutePowerActionConstMeta => const TaskConstMeta(
    debugName: "execute_power_action",
    argNames: ["action"],
  );

  @override
  Future<bool> crateApiFocusWorkspace({required String label}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(label, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFocusWorkspaceConstMeta,
        argValues: [label],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusWorkspaceConstMeta =>
      const TaskConstMeta(debugName: "focus_workspace", argNames: ["label"]);

  @override
  Future<AliceConfig> crateApiLoadConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_alice_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLoadConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadConfigConstMeta =>
      const TaskConstMeta(debugName: "load_config", argNames: []);

  @override
  Future<bool> crateApiSeekMedia({required PlatformInt64 positionMicros}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(positionMicros, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSeekMediaConstMeta,
        argValues: [positionMicros],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSeekMediaConstMeta => const TaskConstMeta(
    debugName: "seek_media",
    argNames: ["positionMicros"],
  );

  @override
  Future<bool> crateApiSendMediaAction({required String action}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(action, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSendMediaActionConstMeta,
        argValues: [action],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendMediaActionConstMeta =>
      const TaskConstMeta(debugName: "send_media_action", argNames: ["action"]);

  @override
  Future<bool> crateApiSendTrayAction({
    required String serviceName,
    required String objectPath,
    required String action,
    required int x,
    required int y,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serviceName, serializer);
          sse_encode_String(objectPath, serializer);
          sse_encode_String(action, serializer);
          sse_encode_i_32(x, serializer);
          sse_encode_i_32(y, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSendTrayActionConstMeta,
        argValues: [serviceName, objectPath, action, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendTrayActionConstMeta => const TaskConstMeta(
    debugName: "send_tray_action",
    argNames: ["serviceName", "objectPath", "action", "x", "y"],
  );

  @override
  Stream<BarSnapshot> crateApiWatchBarSnapshots() {
    final sink = RustStreamSink<BarSnapshot>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_bar_snapshot_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiWatchBarSnapshotsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiWatchBarSnapshotsConstMeta =>
      const TaskConstMeta(debugName: "watch_bar_snapshots", argNames: ["sink"]);

  @override
  Stream<PanelCommand?> crateApiWatchPanelCommands() {
    final sink = RustStreamSink<PanelCommand?>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_opt_box_autoadd_panel_command_Sse(
              sink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiWatchPanelCommandsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiWatchPanelCommandsConstMeta => const TaskConstMeta(
    debugName: "watch_panel_commands",
    argNames: ["sink"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<BarSnapshot> dco_decode_StreamSink_bar_snapshot_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<PanelCommand?>
  dco_decode_StreamSink_opt_box_autoadd_panel_command_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AliceConfig dco_decode_alice_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AliceConfig(
      themeMode: dco_decode_theme_mode(arr[0]),
      accentColor: dco_decode_String(arr[1]),
      showNetworkLabel: dco_decode_bool(arr[2]),
      maxVisibleTrayItems: dco_decode_u_32(arr[3]),
      localTimeZoneLabel: dco_decode_opt_String(arr[4]),
      timeZones: dco_decode_list_time_zone_config(arr[5]),
      powerCommands: dco_decode_power_command_config(arr[6]),
    );
  }

  @protected
  BarSnapshot dco_decode_bar_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BarSnapshot(
      workspaces: dco_decode_list_workspace_snapshot(arr[0]),
      media: dco_decode_opt_box_autoadd_media_snapshot(arr[1]),
      memoryUsagePercent: dco_decode_f_64(arr[2]),
      cpuUsageCores: dco_decode_f_64(arr[3]),
      network: dco_decode_network_snapshot(arr[4]),
      clock: dco_decode_clock_snapshot(arr[5]),
      trayItems: dco_decode_list_tray_item_snapshot(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MediaSnapshot dco_decode_box_autoadd_media_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_media_snapshot(raw);
  }

  @protected
  PanelCommand dco_decode_box_autoadd_panel_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_panel_command(raw);
  }

  @protected
  ClockSnapshot dco_decode_clock_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ClockSnapshot(
      timeZoneCode: dco_decode_String(arr[0]),
      dateLabel: dco_decode_String(arr[1]),
      timeLabel: dco_decode_String(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TimeZoneConfig> dco_decode_list_time_zone_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_time_zone_config).toList();
  }

  @protected
  List<TrayItemSnapshot> dco_decode_list_tray_item_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tray_item_snapshot).toList();
  }

  @protected
  List<WorkspaceSnapshot> dco_decode_list_workspace_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_workspace_snapshot).toList();
  }

  @protected
  MediaSnapshot dco_decode_media_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return MediaSnapshot(
      title: dco_decode_String(arr[0]),
      artist: dco_decode_String(arr[1]),
      albumTitle: dco_decode_String(arr[2]),
      artUrl: dco_decode_String(arr[3]),
      positionLabel: dco_decode_String(arr[4]),
      lengthLabel: dco_decode_String(arr[5]),
      positionMicros: dco_decode_i_64(arr[6]),
      lengthMicros: dco_decode_i_64(arr[7]),
      isPlaying: dco_decode_bool(arr[8]),
    );
  }

  @protected
  NetworkKind dco_decode_network_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetworkKind.values[raw as int];
  }

  @protected
  NetworkSnapshot dco_decode_network_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NetworkSnapshot(
      kind: dco_decode_network_kind(arr[0]),
      label: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  MediaSnapshot? dco_decode_opt_box_autoadd_media_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_media_snapshot(raw);
  }

  @protected
  PanelCommand? dco_decode_opt_box_autoadd_panel_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_panel_command(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  PanelCommand dco_decode_panel_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PanelCommand(
      panelId: dco_decode_String(arr[0]),
      includeIconBytes: dco_decode_bool(arr[1]),
      anchorX: dco_decode_f_64(arr[2]),
      anchorY: dco_decode_f_64(arr[3]),
      width: dco_decode_f_64(arr[4]),
      height: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  PowerCommandConfig dco_decode_power_command_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PowerCommandConfig(
      lock: dco_decode_String(arr[0]),
      lockAndSuspend: dco_decode_String(arr[1]),
      restart: dco_decode_String(arr[2]),
      poweroff: dco_decode_String(arr[3]),
    );
  }

  @protected
  ThemeMode dco_decode_theme_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ThemeMode.values[raw as int];
  }

  @protected
  TimeZoneConfig dco_decode_time_zone_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TimeZoneConfig(
      label: dco_decode_String(arr[0]),
      offsetHours: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  TrayItemSnapshot dco_decode_tray_item_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TrayItemSnapshot(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      serviceName: dco_decode_String(arr[2]),
      objectPath: dco_decode_String(arr[3]),
      iconPngBytes: dco_decode_opt_list_prim_u_8_strict(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WorkspaceSnapshot dco_decode_workspace_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WorkspaceSnapshot(
      label: dco_decode_String(arr[0]),
      isFocused: dco_decode_bool(arr[1]),
      isVisible: dco_decode_bool(arr[2]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<BarSnapshot> sse_decode_StreamSink_bar_snapshot_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<PanelCommand?>
  sse_decode_StreamSink_opt_box_autoadd_panel_command_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AliceConfig sse_decode_alice_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_themeMode = sse_decode_theme_mode(deserializer);
    var var_accentColor = sse_decode_String(deserializer);
    var var_showNetworkLabel = sse_decode_bool(deserializer);
    var var_maxVisibleTrayItems = sse_decode_u_32(deserializer);
    var var_localTimeZoneLabel = sse_decode_opt_String(deserializer);
    var var_timeZones = sse_decode_list_time_zone_config(deserializer);
    var var_powerCommands = sse_decode_power_command_config(deserializer);
    return AliceConfig(
      themeMode: var_themeMode,
      accentColor: var_accentColor,
      showNetworkLabel: var_showNetworkLabel,
      maxVisibleTrayItems: var_maxVisibleTrayItems,
      localTimeZoneLabel: var_localTimeZoneLabel,
      timeZones: var_timeZones,
      powerCommands: var_powerCommands,
    );
  }

  @protected
  BarSnapshot sse_decode_bar_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_workspaces = sse_decode_list_workspace_snapshot(deserializer);
    var var_media = sse_decode_opt_box_autoadd_media_snapshot(deserializer);
    var var_memoryUsagePercent = sse_decode_f_64(deserializer);
    var var_cpuUsageCores = sse_decode_f_64(deserializer);
    var var_network = sse_decode_network_snapshot(deserializer);
    var var_clock = sse_decode_clock_snapshot(deserializer);
    var var_trayItems = sse_decode_list_tray_item_snapshot(deserializer);
    return BarSnapshot(
      workspaces: var_workspaces,
      media: var_media,
      memoryUsagePercent: var_memoryUsagePercent,
      cpuUsageCores: var_cpuUsageCores,
      network: var_network,
      clock: var_clock,
      trayItems: var_trayItems,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MediaSnapshot sse_decode_box_autoadd_media_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_media_snapshot(deserializer));
  }

  @protected
  PanelCommand sse_decode_box_autoadd_panel_command(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_panel_command(deserializer));
  }

  @protected
  ClockSnapshot sse_decode_clock_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timeZoneCode = sse_decode_String(deserializer);
    var var_dateLabel = sse_decode_String(deserializer);
    var var_timeLabel = sse_decode_String(deserializer);
    return ClockSnapshot(
      timeZoneCode: var_timeZoneCode,
      dateLabel: var_dateLabel,
      timeLabel: var_timeLabel,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TimeZoneConfig> sse_decode_list_time_zone_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TimeZoneConfig>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_time_zone_config(deserializer));
    }
    return ans_;
  }

  @protected
  List<TrayItemSnapshot> sse_decode_list_tray_item_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrayItemSnapshot>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tray_item_snapshot(deserializer));
    }
    return ans_;
  }

  @protected
  List<WorkspaceSnapshot> sse_decode_list_workspace_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WorkspaceSnapshot>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_workspace_snapshot(deserializer));
    }
    return ans_;
  }

  @protected
  MediaSnapshot sse_decode_media_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_albumTitle = sse_decode_String(deserializer);
    var var_artUrl = sse_decode_String(deserializer);
    var var_positionLabel = sse_decode_String(deserializer);
    var var_lengthLabel = sse_decode_String(deserializer);
    var var_positionMicros = sse_decode_i_64(deserializer);
    var var_lengthMicros = sse_decode_i_64(deserializer);
    var var_isPlaying = sse_decode_bool(deserializer);
    return MediaSnapshot(
      title: var_title,
      artist: var_artist,
      albumTitle: var_albumTitle,
      artUrl: var_artUrl,
      positionLabel: var_positionLabel,
      lengthLabel: var_lengthLabel,
      positionMicros: var_positionMicros,
      lengthMicros: var_lengthMicros,
      isPlaying: var_isPlaying,
    );
  }

  @protected
  NetworkKind sse_decode_network_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return NetworkKind.values[inner];
  }

  @protected
  NetworkSnapshot sse_decode_network_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_network_kind(deserializer);
    var var_label = sse_decode_String(deserializer);
    return NetworkSnapshot(kind: var_kind, label: var_label);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MediaSnapshot? sse_decode_opt_box_autoadd_media_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_media_snapshot(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PanelCommand? sse_decode_opt_box_autoadd_panel_command(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_panel_command(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PanelCommand sse_decode_panel_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_panelId = sse_decode_String(deserializer);
    var var_includeIconBytes = sse_decode_bool(deserializer);
    var var_anchorX = sse_decode_f_64(deserializer);
    var var_anchorY = sse_decode_f_64(deserializer);
    var var_width = sse_decode_f_64(deserializer);
    var var_height = sse_decode_f_64(deserializer);
    return PanelCommand(
      panelId: var_panelId,
      includeIconBytes: var_includeIconBytes,
      anchorX: var_anchorX,
      anchorY: var_anchorY,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  PowerCommandConfig sse_decode_power_command_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lock = sse_decode_String(deserializer);
    var var_lockAndSuspend = sse_decode_String(deserializer);
    var var_restart = sse_decode_String(deserializer);
    var var_poweroff = sse_decode_String(deserializer);
    return PowerCommandConfig(
      lock: var_lock,
      lockAndSuspend: var_lockAndSuspend,
      restart: var_restart,
      poweroff: var_poweroff,
    );
  }

  @protected
  ThemeMode sse_decode_theme_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ThemeMode.values[inner];
  }

  @protected
  TimeZoneConfig sse_decode_time_zone_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_offsetHours = sse_decode_i_32(deserializer);
    return TimeZoneConfig(label: var_label, offsetHours: var_offsetHours);
  }

  @protected
  TrayItemSnapshot sse_decode_tray_item_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_serviceName = sse_decode_String(deserializer);
    var var_objectPath = sse_decode_String(deserializer);
    var var_iconPngBytes = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return TrayItemSnapshot(
      id: var_id,
      label: var_label,
      serviceName: var_serviceName,
      objectPath: var_objectPath,
      iconPngBytes: var_iconPngBytes,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WorkspaceSnapshot sse_decode_workspace_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_isFocused = sse_decode_bool(deserializer);
    var var_isVisible = sse_decode_bool(deserializer);
    return WorkspaceSnapshot(
      label: var_label,
      isFocused: var_isFocused,
      isVisible: var_isVisible,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_bar_snapshot_Sse(
    RustStreamSink<BarSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_bar_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_opt_box_autoadd_panel_command_Sse(
    RustStreamSink<PanelCommand?> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_panel_command,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_alice_config(AliceConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_theme_mode(self.themeMode, serializer);
    sse_encode_String(self.accentColor, serializer);
    sse_encode_bool(self.showNetworkLabel, serializer);
    sse_encode_u_32(self.maxVisibleTrayItems, serializer);
    sse_encode_opt_String(self.localTimeZoneLabel, serializer);
    sse_encode_list_time_zone_config(self.timeZones, serializer);
    sse_encode_power_command_config(self.powerCommands, serializer);
  }

  @protected
  void sse_encode_bar_snapshot(BarSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_workspace_snapshot(self.workspaces, serializer);
    sse_encode_opt_box_autoadd_media_snapshot(self.media, serializer);
    sse_encode_f_64(self.memoryUsagePercent, serializer);
    sse_encode_f_64(self.cpuUsageCores, serializer);
    sse_encode_network_snapshot(self.network, serializer);
    sse_encode_clock_snapshot(self.clock, serializer);
    sse_encode_list_tray_item_snapshot(self.trayItems, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_media_snapshot(
    MediaSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_snapshot(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_panel_command(
    PanelCommand self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_panel_command(self, serializer);
  }

  @protected
  void sse_encode_clock_snapshot(ClockSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.timeZoneCode, serializer);
    sse_encode_String(self.dateLabel, serializer);
    sse_encode_String(self.timeLabel, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_time_zone_config(
    List<TimeZoneConfig> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_time_zone_config(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tray_item_snapshot(
    List<TrayItemSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tray_item_snapshot(item, serializer);
    }
  }

  @protected
  void sse_encode_list_workspace_snapshot(
    List<WorkspaceSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_workspace_snapshot(item, serializer);
    }
  }

  @protected
  void sse_encode_media_snapshot(MediaSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.albumTitle, serializer);
    sse_encode_String(self.artUrl, serializer);
    sse_encode_String(self.positionLabel, serializer);
    sse_encode_String(self.lengthLabel, serializer);
    sse_encode_i_64(self.positionMicros, serializer);
    sse_encode_i_64(self.lengthMicros, serializer);
    sse_encode_bool(self.isPlaying, serializer);
  }

  @protected
  void sse_encode_network_kind(NetworkKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_network_snapshot(
    NetworkSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_network_kind(self.kind, serializer);
    sse_encode_String(self.label, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_media_snapshot(
    MediaSnapshot? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_media_snapshot(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_panel_command(
    PanelCommand? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_panel_command(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_panel_command(PanelCommand self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.panelId, serializer);
    sse_encode_bool(self.includeIconBytes, serializer);
    sse_encode_f_64(self.anchorX, serializer);
    sse_encode_f_64(self.anchorY, serializer);
    sse_encode_f_64(self.width, serializer);
    sse_encode_f_64(self.height, serializer);
  }

  @protected
  void sse_encode_power_command_config(
    PowerCommandConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.lock, serializer);
    sse_encode_String(self.lockAndSuspend, serializer);
    sse_encode_String(self.restart, serializer);
    sse_encode_String(self.poweroff, serializer);
  }

  @protected
  void sse_encode_theme_mode(ThemeMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_time_zone_config(
    TimeZoneConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_i_32(self.offsetHours, serializer);
  }

  @protected
  void sse_encode_tray_item_snapshot(
    TrayItemSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.serviceName, serializer);
    sse_encode_String(self.objectPath, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.iconPngBytes, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_workspace_snapshot(
    WorkspaceSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_bool(self.isFocused, serializer);
    sse_encode_bool(self.isVisible, serializer);
  }
}
