// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'caldav/models.dart';
import 'config.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'state.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<BarSnapshot> dco_decode_StreamSink_bar_snapshot_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<BarViewLifecycle> dco_decode_StreamSink_bar_view_lifecycle_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PanelCommand?>
  dco_decode_StreamSink_opt_box_autoadd_panel_command_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AliceUiConfig dco_decode_alice_ui_config(dynamic raw);

  @protected
  BarSnapshot dco_decode_bar_snapshot(dynamic raw);

  @protected
  BarViewLifecycle dco_decode_bar_view_lifecycle(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CalDavUiConfig dco_decode_box_autoadd_cal_dav_ui_config(dynamic raw);

  @protected
  CalendarConfig dco_decode_box_autoadd_calendar_config(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MediaSnapshot dco_decode_box_autoadd_media_snapshot(dynamic raw);

  @protected
  PanelCommand dco_decode_box_autoadd_panel_command(dynamic raw);

  @protected
  TaskResourceIdentity dco_decode_box_autoadd_task_resource_identity(
    dynamic raw,
  );

  @protected
  WeatherSnapshot dco_decode_box_autoadd_weather_snapshot(dynamic raw);

  @protected
  CalDavFreshness dco_decode_cal_dav_freshness(dynamic raw);

  @protected
  CalDavSyncState dco_decode_cal_dav_sync_state(dynamic raw);

  @protected
  CalDavUiConfig dco_decode_cal_dav_ui_config(dynamic raw);

  @protected
  CalendarConfig dco_decode_calendar_config(dynamic raw);

  @protected
  CalendarEvent dco_decode_calendar_event(dynamic raw);

  @protected
  CalendarFetchResult dco_decode_calendar_fetch_result(dynamic raw);

  @protected
  ClockSnapshot dco_decode_clock_snapshot(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CalendarEvent> dco_decode_list_calendar_event(dynamic raw);

  @protected
  List<NormalizedTask> dco_decode_list_normalized_task(dynamic raw);

  @protected
  List<NotificationActionSnapshot> dco_decode_list_notification_action_snapshot(
    dynamic raw,
  );

  @protected
  List<NotificationSnapshot> dco_decode_list_notification_snapshot(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TimeZoneConfig> dco_decode_list_time_zone_config(dynamic raw);

  @protected
  List<TrayItemSnapshot> dco_decode_list_tray_item_snapshot(dynamic raw);

  @protected
  List<WeatherAlert> dco_decode_list_weather_alert(dynamic raw);

  @protected
  List<WeatherDay> dco_decode_list_weather_day(dynamic raw);

  @protected
  List<WeatherPoint> dco_decode_list_weather_point(dynamic raw);

  @protected
  List<WorkspaceSnapshot> dco_decode_list_workspace_snapshot(dynamic raw);

  @protected
  MediaSnapshot dco_decode_media_snapshot(dynamic raw);

  @protected
  NetworkKind dco_decode_network_kind(dynamic raw);

  @protected
  NetworkSnapshot dco_decode_network_snapshot(dynamic raw);

  @protected
  NormalizedTask dco_decode_normalized_task(dynamic raw);

  @protected
  NotificationActionSnapshot dco_decode_notification_action_snapshot(
    dynamic raw,
  );

  @protected
  NotificationConfig dco_decode_notification_config(dynamic raw);

  @protected
  NotificationSnapshot dco_decode_notification_snapshot(dynamic raw);

  @protected
  NotificationUrgency dco_decode_notification_urgency(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CalDavUiConfig? dco_decode_opt_box_autoadd_cal_dav_ui_config(dynamic raw);

  @protected
  CalendarConfig? dco_decode_opt_box_autoadd_calendar_config(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MediaSnapshot? dco_decode_opt_box_autoadd_media_snapshot(dynamic raw);

  @protected
  PanelCommand? dco_decode_opt_box_autoadd_panel_command(dynamic raw);

  @protected
  WeatherSnapshot? dco_decode_opt_box_autoadd_weather_snapshot(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PanelCommand dco_decode_panel_command(dynamic raw);

  @protected
  PowerCommandConfig dco_decode_power_command_config(dynamic raw);

  @protected
  TaskPriority dco_decode_task_priority(dynamic raw);

  @protected
  TaskResourceIdentity dco_decode_task_resource_identity(dynamic raw);

  @protected
  TaskStatus dco_decode_task_status(dynamic raw);

  @protected
  ThemeMode dco_decode_theme_mode(dynamic raw);

  @protected
  TimeZoneConfig dco_decode_time_zone_config(dynamic raw);

  @protected
  TrayItemSnapshot dco_decode_tray_item_snapshot(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WeatherAlert dco_decode_weather_alert(dynamic raw);

  @protected
  WeatherConfig dco_decode_weather_config(dynamic raw);

  @protected
  WeatherDay dco_decode_weather_day(dynamic raw);

  @protected
  WeatherPoint dco_decode_weather_point(dynamic raw);

  @protected
  WeatherSnapshot dco_decode_weather_snapshot(dynamic raw);

  @protected
  WorkspaceSnapshot dco_decode_workspace_snapshot(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<BarSnapshot> sse_decode_StreamSink_bar_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BarViewLifecycle> sse_decode_StreamSink_bar_view_lifecycle_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PanelCommand?>
  sse_decode_StreamSink_opt_box_autoadd_panel_command_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AliceUiConfig sse_decode_alice_ui_config(SseDeserializer deserializer);

  @protected
  BarSnapshot sse_decode_bar_snapshot(SseDeserializer deserializer);

  @protected
  BarViewLifecycle sse_decode_bar_view_lifecycle(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CalDavUiConfig sse_decode_box_autoadd_cal_dav_ui_config(
    SseDeserializer deserializer,
  );

  @protected
  CalendarConfig sse_decode_box_autoadd_calendar_config(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MediaSnapshot sse_decode_box_autoadd_media_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  PanelCommand sse_decode_box_autoadd_panel_command(
    SseDeserializer deserializer,
  );

  @protected
  TaskResourceIdentity sse_decode_box_autoadd_task_resource_identity(
    SseDeserializer deserializer,
  );

  @protected
  WeatherSnapshot sse_decode_box_autoadd_weather_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  CalDavFreshness sse_decode_cal_dav_freshness(SseDeserializer deserializer);

  @protected
  CalDavSyncState sse_decode_cal_dav_sync_state(SseDeserializer deserializer);

  @protected
  CalDavUiConfig sse_decode_cal_dav_ui_config(SseDeserializer deserializer);

  @protected
  CalendarConfig sse_decode_calendar_config(SseDeserializer deserializer);

  @protected
  CalendarEvent sse_decode_calendar_event(SseDeserializer deserializer);

  @protected
  CalendarFetchResult sse_decode_calendar_fetch_result(
    SseDeserializer deserializer,
  );

  @protected
  ClockSnapshot sse_decode_clock_snapshot(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CalendarEvent> sse_decode_list_calendar_event(
    SseDeserializer deserializer,
  );

  @protected
  List<NormalizedTask> sse_decode_list_normalized_task(
    SseDeserializer deserializer,
  );

  @protected
  List<NotificationActionSnapshot> sse_decode_list_notification_action_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<NotificationSnapshot> sse_decode_list_notification_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TimeZoneConfig> sse_decode_list_time_zone_config(
    SseDeserializer deserializer,
  );

  @protected
  List<TrayItemSnapshot> sse_decode_list_tray_item_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<WeatherAlert> sse_decode_list_weather_alert(
    SseDeserializer deserializer,
  );

  @protected
  List<WeatherDay> sse_decode_list_weather_day(SseDeserializer deserializer);

  @protected
  List<WeatherPoint> sse_decode_list_weather_point(
    SseDeserializer deserializer,
  );

  @protected
  List<WorkspaceSnapshot> sse_decode_list_workspace_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  MediaSnapshot sse_decode_media_snapshot(SseDeserializer deserializer);

  @protected
  NetworkKind sse_decode_network_kind(SseDeserializer deserializer);

  @protected
  NetworkSnapshot sse_decode_network_snapshot(SseDeserializer deserializer);

  @protected
  NormalizedTask sse_decode_normalized_task(SseDeserializer deserializer);

  @protected
  NotificationActionSnapshot sse_decode_notification_action_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  NotificationConfig sse_decode_notification_config(
    SseDeserializer deserializer,
  );

  @protected
  NotificationSnapshot sse_decode_notification_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  NotificationUrgency sse_decode_notification_urgency(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CalDavUiConfig? sse_decode_opt_box_autoadd_cal_dav_ui_config(
    SseDeserializer deserializer,
  );

  @protected
  CalendarConfig? sse_decode_opt_box_autoadd_calendar_config(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MediaSnapshot? sse_decode_opt_box_autoadd_media_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  PanelCommand? sse_decode_opt_box_autoadd_panel_command(
    SseDeserializer deserializer,
  );

  @protected
  WeatherSnapshot? sse_decode_opt_box_autoadd_weather_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PanelCommand sse_decode_panel_command(SseDeserializer deserializer);

  @protected
  PowerCommandConfig sse_decode_power_command_config(
    SseDeserializer deserializer,
  );

  @protected
  TaskPriority sse_decode_task_priority(SseDeserializer deserializer);

  @protected
  TaskResourceIdentity sse_decode_task_resource_identity(
    SseDeserializer deserializer,
  );

  @protected
  TaskStatus sse_decode_task_status(SseDeserializer deserializer);

  @protected
  ThemeMode sse_decode_theme_mode(SseDeserializer deserializer);

  @protected
  TimeZoneConfig sse_decode_time_zone_config(SseDeserializer deserializer);

  @protected
  TrayItemSnapshot sse_decode_tray_item_snapshot(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WeatherAlert sse_decode_weather_alert(SseDeserializer deserializer);

  @protected
  WeatherConfig sse_decode_weather_config(SseDeserializer deserializer);

  @protected
  WeatherDay sse_decode_weather_day(SseDeserializer deserializer);

  @protected
  WeatherPoint sse_decode_weather_point(SseDeserializer deserializer);

  @protected
  WeatherSnapshot sse_decode_weather_snapshot(SseDeserializer deserializer);

  @protected
  WorkspaceSnapshot sse_decode_workspace_snapshot(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bar_snapshot_Sse(
    RustStreamSink<BarSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bar_view_lifecycle_Sse(
    RustStreamSink<BarViewLifecycle> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_opt_box_autoadd_panel_command_Sse(
    RustStreamSink<PanelCommand?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_alice_ui_config(AliceUiConfig self, SseSerializer serializer);

  @protected
  void sse_encode_bar_snapshot(BarSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_bar_view_lifecycle(
    BarViewLifecycle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cal_dav_ui_config(
    CalDavUiConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_calendar_config(
    CalendarConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_media_snapshot(
    MediaSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_panel_command(
    PanelCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_task_resource_identity(
    TaskResourceIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_weather_snapshot(
    WeatherSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cal_dav_freshness(
    CalDavFreshness self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cal_dav_sync_state(
    CalDavSyncState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cal_dav_ui_config(
    CalDavUiConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_calendar_config(
    CalendarConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_calendar_event(CalendarEvent self, SseSerializer serializer);

  @protected
  void sse_encode_calendar_fetch_result(
    CalendarFetchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clock_snapshot(ClockSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_calendar_event(
    List<CalendarEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_normalized_task(
    List<NormalizedTask> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_notification_action_snapshot(
    List<NotificationActionSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_notification_snapshot(
    List<NotificationSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_time_zone_config(
    List<TimeZoneConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tray_item_snapshot(
    List<TrayItemSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_weather_alert(
    List<WeatherAlert> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_weather_day(
    List<WeatherDay> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_weather_point(
    List<WeatherPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_snapshot(
    List<WorkspaceSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_snapshot(MediaSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_network_kind(NetworkKind self, SseSerializer serializer);

  @protected
  void sse_encode_network_snapshot(
    NetworkSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_normalized_task(
    NormalizedTask self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_action_snapshot(
    NotificationActionSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_config(
    NotificationConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_snapshot(
    NotificationSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_urgency(
    NotificationUrgency self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_cal_dav_ui_config(
    CalDavUiConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_calendar_config(
    CalendarConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_media_snapshot(
    MediaSnapshot? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_panel_command(
    PanelCommand? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_weather_snapshot(
    WeatherSnapshot? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_panel_command(PanelCommand self, SseSerializer serializer);

  @protected
  void sse_encode_power_command_config(
    PowerCommandConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_task_priority(TaskPriority self, SseSerializer serializer);

  @protected
  void sse_encode_task_resource_identity(
    TaskResourceIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_task_status(TaskStatus self, SseSerializer serializer);

  @protected
  void sse_encode_theme_mode(ThemeMode self, SseSerializer serializer);

  @protected
  void sse_encode_time_zone_config(
    TimeZoneConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tray_item_snapshot(
    TrayItemSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_weather_alert(WeatherAlert self, SseSerializer serializer);

  @protected
  void sse_encode_weather_config(WeatherConfig self, SseSerializer serializer);

  @protected
  void sse_encode_weather_day(WeatherDay self, SseSerializer serializer);

  @protected
  void sse_encode_weather_point(WeatherPoint self, SseSerializer serializer);

  @protected
  void sse_encode_weather_snapshot(
    WeatherSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_snapshot(
    WorkspaceSnapshot self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
