// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BarSnapshot {
  final List<WorkspaceSnapshot> workspaces;
  final MediaSnapshot? media;
  final double memoryUsagePercent;
  final double cpuUsageCores;
  final NetworkSnapshot network;
  final ClockSnapshot clock;
  final WeatherSnapshot? weather;
  final List<TrayItemSnapshot> trayItems;
  final List<NotificationSnapshot> notifications;

  const BarSnapshot({
    required this.workspaces,
    this.media,
    required this.memoryUsagePercent,
    required this.cpuUsageCores,
    required this.network,
    required this.clock,
    this.weather,
    required this.trayItems,
    required this.notifications,
  });

  @override
  int get hashCode =>
      workspaces.hashCode ^
      media.hashCode ^
      memoryUsagePercent.hashCode ^
      cpuUsageCores.hashCode ^
      network.hashCode ^
      clock.hashCode ^
      weather.hashCode ^
      trayItems.hashCode ^
      notifications.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BarSnapshot &&
          runtimeType == other.runtimeType &&
          workspaces == other.workspaces &&
          media == other.media &&
          memoryUsagePercent == other.memoryUsagePercent &&
          cpuUsageCores == other.cpuUsageCores &&
          network == other.network &&
          clock == other.clock &&
          weather == other.weather &&
          trayItems == other.trayItems &&
          notifications == other.notifications;
}

class CalendarEvent {
  final String id;
  final String title;
  final bool isAllDay;

  /// `"HH:MM"` in local time, or empty for all-day events.
  final String startLabel;

  /// `"HH:MM"` in local time, or empty for all-day events.
  final String endLabel;
  final String calendarName;

  /// `"#RRGGBB"` hex color, or `""` if unknown.
  final String calendarColor;

  const CalendarEvent({
    required this.id,
    required this.title,
    required this.isAllDay,
    required this.startLabel,
    required this.endLabel,
    required this.calendarName,
    required this.calendarColor,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      isAllDay.hashCode ^
      startLabel.hashCode ^
      endLabel.hashCode ^
      calendarName.hashCode ^
      calendarColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          isAllDay == other.isAllDay &&
          startLabel == other.startLabel &&
          endLabel == other.endLabel &&
          calendarName == other.calendarName &&
          calendarColor == other.calendarColor;
}

class CalendarFetchResult {
  /// `"not_configured"` | `"needs_auth"` | `"polling"` | `"ready"` | `"error"`
  final String status;
  final List<CalendarEvent> events;
  final String? authUrl;
  final String? authCode;
  final String? errorMessage;

  const CalendarFetchResult({
    required this.status,
    required this.events,
    this.authUrl,
    this.authCode,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      events.hashCode ^
      authUrl.hashCode ^
      authCode.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarFetchResult &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          events == other.events &&
          authUrl == other.authUrl &&
          authCode == other.authCode &&
          errorMessage == other.errorMessage;
}

class ClockSnapshot {
  final String timeZoneCode;
  final String dateLabel;
  final String timeLabel;

  const ClockSnapshot({
    required this.timeZoneCode,
    required this.dateLabel,
    required this.timeLabel,
  });

  @override
  int get hashCode =>
      timeZoneCode.hashCode ^ dateLabel.hashCode ^ timeLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClockSnapshot &&
          runtimeType == other.runtimeType &&
          timeZoneCode == other.timeZoneCode &&
          dateLabel == other.dateLabel &&
          timeLabel == other.timeLabel;
}

class MediaSnapshot {
  final String title;
  final String artist;
  final String albumTitle;
  final String artUrl;
  final String positionLabel;
  final String lengthLabel;
  final PlatformInt64 positionMicros;
  final PlatformInt64 lengthMicros;
  final bool isPlaying;

  const MediaSnapshot({
    required this.title,
    required this.artist,
    required this.albumTitle,
    required this.artUrl,
    required this.positionLabel,
    required this.lengthLabel,
    required this.positionMicros,
    required this.lengthMicros,
    required this.isPlaying,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      albumTitle.hashCode ^
      artUrl.hashCode ^
      positionLabel.hashCode ^
      lengthLabel.hashCode ^
      positionMicros.hashCode ^
      lengthMicros.hashCode ^
      isPlaying.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaSnapshot &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          albumTitle == other.albumTitle &&
          artUrl == other.artUrl &&
          positionLabel == other.positionLabel &&
          lengthLabel == other.lengthLabel &&
          positionMicros == other.positionMicros &&
          lengthMicros == other.lengthMicros &&
          isPlaying == other.isPlaying;
}

enum NetworkKind { wifi, wired, disconnected }

class NetworkSnapshot {
  final NetworkKind kind;
  final String label;

  const NetworkSnapshot({required this.kind, required this.label});

  @override
  int get hashCode => kind.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkSnapshot &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          label == other.label;
}

class NotificationActionSnapshot {
  final String key;
  final String label;

  const NotificationActionSnapshot({required this.key, required this.label});

  @override
  int get hashCode => key.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationActionSnapshot &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label;
}

class NotificationSnapshot {
  final int id;
  final String appName;

  /// Icon name or file path. Flutter uses priority: image_data > image_path > app_icon.
  final String appIcon;
  final String summary;
  final String body;
  final NotificationUrgency urgency;
  final List<NotificationActionSnapshot> actions;

  /// Freedesktop notification category (e.g. `"email"`, `"im.received"`).
  final String? category;
  final bool isRead;

  /// Unix timestamp (seconds) when the notification was received.
  final BigInt receivedAtUnixSecs;

  /// PNG-encoded image bytes from the `image-data` hint, if present.
  final Uint8List? imageData;

  /// File path or `file://` URI from the `image-path` hint, if present.
  final String? imagePath;

  const NotificationSnapshot({
    required this.id,
    required this.appName,
    required this.appIcon,
    required this.summary,
    required this.body,
    required this.urgency,
    required this.actions,
    this.category,
    required this.isRead,
    required this.receivedAtUnixSecs,
    this.imageData,
    this.imagePath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      appName.hashCode ^
      appIcon.hashCode ^
      summary.hashCode ^
      body.hashCode ^
      urgency.hashCode ^
      actions.hashCode ^
      category.hashCode ^
      isRead.hashCode ^
      receivedAtUnixSecs.hashCode ^
      imageData.hashCode ^
      imagePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          appName == other.appName &&
          appIcon == other.appIcon &&
          summary == other.summary &&
          body == other.body &&
          urgency == other.urgency &&
          actions == other.actions &&
          category == other.category &&
          isRead == other.isRead &&
          receivedAtUnixSecs == other.receivedAtUnixSecs &&
          imageData == other.imageData &&
          imagePath == other.imagePath;
}

enum NotificationUrgency { low, normal, critical }

class TrayItemSnapshot {
  final String id;
  final String label;
  final String serviceName;
  final String objectPath;
  final Uint8List? iconPngBytes;

  const TrayItemSnapshot({
    required this.id,
    required this.label,
    required this.serviceName,
    required this.objectPath,
    this.iconPngBytes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      serviceName.hashCode ^
      objectPath.hashCode ^
      iconPngBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrayItemSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          serviceName == other.serviceName &&
          objectPath == other.objectPath &&
          iconPngBytes == other.iconPngBytes;
}

class WeatherAlert {
  final String title;
  final String description;
  final String severity;
  final PlatformInt64? time;
  final PlatformInt64? expires;

  const WeatherAlert({
    required this.title,
    required this.description,
    required this.severity,
    this.time,
    this.expires,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      description.hashCode ^
      severity.hashCode ^
      time.hashCode ^
      expires.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherAlert &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          description == other.description &&
          severity == other.severity &&
          time == other.time &&
          expires == other.expires;
}

class WeatherDay {
  final PlatformInt64 time;
  final String summary;
  final String icon;
  final double? moonPhase;
  final double? temperatureHigh;
  final double? temperatureLow;
  final double? humidity;
  final double? precipProbability;
  final double? windSpeed;
  final double? windBearing;

  const WeatherDay({
    required this.time,
    required this.summary,
    required this.icon,
    this.moonPhase,
    this.temperatureHigh,
    this.temperatureLow,
    this.humidity,
    this.precipProbability,
    this.windSpeed,
    this.windBearing,
  });

  @override
  int get hashCode =>
      time.hashCode ^
      summary.hashCode ^
      icon.hashCode ^
      moonPhase.hashCode ^
      temperatureHigh.hashCode ^
      temperatureLow.hashCode ^
      humidity.hashCode ^
      precipProbability.hashCode ^
      windSpeed.hashCode ^
      windBearing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherDay &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          summary == other.summary &&
          icon == other.icon &&
          moonPhase == other.moonPhase &&
          temperatureHigh == other.temperatureHigh &&
          temperatureLow == other.temperatureLow &&
          humidity == other.humidity &&
          precipProbability == other.precipProbability &&
          windSpeed == other.windSpeed &&
          windBearing == other.windBearing;
}

class WeatherPoint {
  final PlatformInt64 time;
  final String summary;
  final String icon;
  final double? temperature;
  final double? humidity;
  final double? precipProbability;
  final double? windSpeed;
  final double? windBearing;

  const WeatherPoint({
    required this.time,
    required this.summary,
    required this.icon,
    this.temperature,
    this.humidity,
    this.precipProbability,
    this.windSpeed,
    this.windBearing,
  });

  @override
  int get hashCode =>
      time.hashCode ^
      summary.hashCode ^
      icon.hashCode ^
      temperature.hashCode ^
      humidity.hashCode ^
      precipProbability.hashCode ^
      windSpeed.hashCode ^
      windBearing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherPoint &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          summary == other.summary &&
          icon == other.icon &&
          temperature == other.temperature &&
          humidity == other.humidity &&
          precipProbability == other.precipProbability &&
          windSpeed == other.windSpeed &&
          windBearing == other.windBearing;
}

class WeatherSnapshot {
  final double latitude;
  final double longitude;
  final String timezone;
  final double offset;
  final String units;
  final PlatformInt64 lastUpdatedUnixSecs;
  final WeatherPoint currently;
  final List<WeatherPoint> hourly;
  final List<WeatherDay> daily;
  final List<WeatherAlert> alerts;

  const WeatherSnapshot({
    required this.latitude,
    required this.longitude,
    required this.timezone,
    required this.offset,
    required this.units,
    required this.lastUpdatedUnixSecs,
    required this.currently,
    required this.hourly,
    required this.daily,
    required this.alerts,
  });

  @override
  int get hashCode =>
      latitude.hashCode ^
      longitude.hashCode ^
      timezone.hashCode ^
      offset.hashCode ^
      units.hashCode ^
      lastUpdatedUnixSecs.hashCode ^
      currently.hashCode ^
      hourly.hashCode ^
      daily.hashCode ^
      alerts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherSnapshot &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          timezone == other.timezone &&
          offset == other.offset &&
          units == other.units &&
          lastUpdatedUnixSecs == other.lastUpdatedUnixSecs &&
          currently == other.currently &&
          hourly == other.hourly &&
          daily == other.daily &&
          alerts == other.alerts;
}

class WorkspaceSnapshot {
  final String label;
  final bool isFocused;
  final bool isVisible;

  const WorkspaceSnapshot({
    required this.label,
    required this.isFocused,
    required this.isVisible,
  });

  @override
  int get hashCode => label.hashCode ^ isFocused.hashCode ^ isVisible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceSnapshot &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          isFocused == other.isFocused &&
          isVisible == other.isVisible;
}
