// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BarSnapshot {
  final List<WorkspaceSnapshot> workspaces;
  final MediaSnapshot? media;
  final double memoryUsagePercent;
  final double cpuUsageCores;
  final NetworkSnapshot network;
  final ClockSnapshot clock;
  final List<TrayItemSnapshot> trayItems;

  const BarSnapshot({
    required this.workspaces,
    this.media,
    required this.memoryUsagePercent,
    required this.cpuUsageCores,
    required this.network,
    required this.clock,
    required this.trayItems,
  });

  @override
  int get hashCode =>
      workspaces.hashCode ^
      media.hashCode ^
      memoryUsagePercent.hashCode ^
      cpuUsageCores.hashCode ^
      network.hashCode ^
      clock.hashCode ^
      trayItems.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BarSnapshot &&
          runtimeType == other.runtimeType &&
          workspaces == other.workspaces &&
          media == other.media &&
          memoryUsagePercent == other.memoryUsagePercent &&
          cpuUsageCores == other.cpuUsageCores &&
          network == other.network &&
          clock == other.clock &&
          trayItems == other.trayItems;
}

class ClockSnapshot {
  final String timeZoneCode;
  final String dateLabel;
  final String timeLabel;

  const ClockSnapshot({
    required this.timeZoneCode,
    required this.dateLabel,
    required this.timeLabel,
  });

  @override
  int get hashCode =>
      timeZoneCode.hashCode ^ dateLabel.hashCode ^ timeLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClockSnapshot &&
          runtimeType == other.runtimeType &&
          timeZoneCode == other.timeZoneCode &&
          dateLabel == other.dateLabel &&
          timeLabel == other.timeLabel;
}

class MediaSnapshot {
  final String title;
  final String artist;
  final String albumTitle;
  final String artUrl;
  final String positionLabel;
  final String lengthLabel;
  final PlatformInt64 positionMicros;
  final PlatformInt64 lengthMicros;
  final bool isPlaying;

  const MediaSnapshot({
    required this.title,
    required this.artist,
    required this.albumTitle,
    required this.artUrl,
    required this.positionLabel,
    required this.lengthLabel,
    required this.positionMicros,
    required this.lengthMicros,
    required this.isPlaying,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      albumTitle.hashCode ^
      artUrl.hashCode ^
      positionLabel.hashCode ^
      lengthLabel.hashCode ^
      positionMicros.hashCode ^
      lengthMicros.hashCode ^
      isPlaying.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaSnapshot &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          albumTitle == other.albumTitle &&
          artUrl == other.artUrl &&
          positionLabel == other.positionLabel &&
          lengthLabel == other.lengthLabel &&
          positionMicros == other.positionMicros &&
          lengthMicros == other.lengthMicros &&
          isPlaying == other.isPlaying;
}

enum NetworkKind { wifi, wired, disconnected }

class NetworkSnapshot {
  final NetworkKind kind;
  final String label;

  const NetworkSnapshot({required this.kind, required this.label});

  @override
  int get hashCode => kind.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkSnapshot &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          label == other.label;
}

class TrayItemSnapshot {
  final String id;
  final String label;
  final String serviceName;
  final String objectPath;
  final Uint8List? iconPngBytes;

  const TrayItemSnapshot({
    required this.id,
    required this.label,
    required this.serviceName,
    required this.objectPath,
    this.iconPngBytes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      serviceName.hashCode ^
      objectPath.hashCode ^
      iconPngBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrayItemSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          serviceName == other.serviceName &&
          objectPath == other.objectPath &&
          iconPngBytes == other.iconPngBytes;
}

class WorkspaceSnapshot {
  final String label;
  final bool isFocused;
  final bool isVisible;

  const WorkspaceSnapshot({
    required this.label,
    required this.isFocused,
    required this.isVisible,
  });

  @override
  int get hashCode => label.hashCode ^ isFocused.hashCode ^ isVisible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceSnapshot &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          isFocused == other.isFocused &&
          isVisible == other.isVisible;
}
