// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TrayMenuNode {
  final int id;
  final String label;
  final bool visible;
  final bool enabled;
  final bool separator;
  final bool submenu;
  final TrayMenuToggle toggle;

  /// -1: indeterminate, 0: off, 1: on.
  final int toggleState;
  final List<TrayMenuNode> children;

  const TrayMenuNode({
    required this.id,
    required this.label,
    required this.visible,
    required this.enabled,
    required this.separator,
    required this.submenu,
    required this.toggle,
    required this.toggleState,
    required this.children,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      visible.hashCode ^
      enabled.hashCode ^
      separator.hashCode ^
      submenu.hashCode ^
      toggle.hashCode ^
      toggleState.hashCode ^
      children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrayMenuNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          visible == other.visible &&
          enabled == other.enabled &&
          separator == other.separator &&
          submenu == other.submenu &&
          toggle == other.toggle &&
          toggleState == other.toggleState &&
          children == other.children;
}

enum TrayMenuToggle { none, check, radio }
