// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'tray.freezed.dart';

@freezed
sealed class TrayActionOutcome with _$TrayActionOutcome {
  const TrayActionOutcome._();

  const factory TrayActionOutcome.executed() = TrayActionOutcome_Executed;
  const factory TrayActionOutcome.unsupported() = TrayActionOutcome_Unsupported;
  const factory TrayActionOutcome.failed({required String reason}) =
      TrayActionOutcome_Failed;
}
