// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'tray_menu.dart';
part 'tray_menu_service.freezed.dart';

@freezed
sealed class TrayMenuSelection with _$TrayMenuSelection {
  const TrayMenuSelection._();

  const factory TrayMenuSelection.remote({required int id}) =
      TrayMenuSelection_Remote;
  const factory TrayMenuSelection.secondary() = TrayMenuSelection_Secondary;
}

class TrayMenuSnapshot {
  final BigInt requestId;
  final int revision;
  final TrayMenuNode root;
  final bool secondarySupported;

  const TrayMenuSnapshot({
    required this.requestId,
    required this.revision,
    required this.root,
    required this.secondarySupported,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      revision.hashCode ^
      root.hashCode ^
      secondarySupported.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrayMenuSnapshot &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          revision == other.revision &&
          root == other.root &&
          secondarySupported == other.secondarySupported;
}

@freezed
sealed class TrayMenuUpdate with _$TrayMenuUpdate {
  const TrayMenuUpdate._();

  const factory TrayMenuUpdate.unchanged() = TrayMenuUpdate_Unchanged;
  const factory TrayMenuUpdate.updated({required TrayMenuSnapshot snapshot}) =
      TrayMenuUpdate_Updated;
  const factory TrayMenuUpdate.closed() = TrayMenuUpdate_Closed;
}
